services:
  api:
    container_name: homemap-api
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    restart: always
    env_file:
      - .env
    environment:
      PORT: 3000
      CACHE_TTL: 1
      JWT_MAX_AGE: 86400
      STAT_BATCH_SIZE: 100
      STAT_FLUSH_INTERVAL: 60
      YAPI_LOGIN_BASE_URL: https://login.yandex.ru
      YAPI_IOT_BASE_URL: https://api.iot.yandex.net/v1.0
      YAPI_OAUTH_BASE_URL: https://oauth.yandex.ru
      YAPI_CLIENT_ID: ${YAPI_CLIENT_ID}
      YAPI_CLIENT_SECRET: ${YAPI_CLIENT_SECRET}
    networks:
      - app-network
    ports:
      - "3000:3000"
    volumes:
      - /homemap/server/appData:/server/packages/api/appData
  app:
    container_name: homemap-app
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    restart: always
    networks:
      - app-network
    ports:
      - "8888:80"
  demo:
    container_name: homemap-demo
    build:
      context: .
      dockerfile: docker/Dockerfile.demo
    restart: always
    networks:
      - app-network
    ports:
      - "8889:80"
  metabase:
    image: metabase/metabase:latest
    container_name: homemap-metabase
    restart: always
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase/storage/h2.db
    networks:
      - app-network
    ports:
      - 3001:3000
    volumes:
      - /homemap/server/appData:/metabase/appData:ro
      - /homemap/metabase:/metabase/storage
networks:
  app-network:
    driver: bridge