# Set base image
FROM node:22.14.0-bullseye

# Set wodking directory
WORKDIR /server

# Copy dependencies
COPY packages/shared packages/shared

# Copy self
COPY packages/api packages/api

# Copy root
COPY tsconfig.json .
COPY package.json .
COPY package-lock.json .

# Build
RUN npm install
RUN npm run build-api

# Expose port from env
EXPOSE $PORT

# Run api when running a container
CMD ["npm", "run", "start-api"]